scheme: http
origins: http://localhost:9080, http://localhost:8080, http://localhost:8180
keycloak-port: 8180
keycloak-issuer: ${scheme}://localhost:${keycloak-port}/realms/twister

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR
server:
  port: 9080
  error:
    include-message: always
  ssl:
    enabled: false

spring:
  jpa:
    open-in-view: false
  mvc:
    static-path-pattern: /resources/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak-issuer}


auth-props:
  issuers:
    - uri: ${keycloak-issuer}
      username-json-path: $.preferred_username
      claims:
        - jsonPath: $.realm_access.roles
        - jsonPath: $.resource_access.*.roles
---
spring:
  config:
    activate:
      on-profile: ssl
scheme: https
keycloak-port: 8443

server:
  ssl:
    enabled: true
---
spring:
  config:
    activate:
      on-profile: qa
hibernate-props:
  props:
    hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.show_sql: true
    hibernate.format_sql: true
    hibernate.use_sql_comments: true
#    hibernate.hbm2ddl.auto: create-drop
---
spring:
  config:
    activate:
      on-profile: prod
hibernate-props:
  props:
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect