---
scheme: http
origins: ${scheme}://localhost:8180/
keycloak-port: 8180
keycloak-realm: twister
keycloak-host: localhost
keycloak-issuer: ${scheme}://${keycloak-host}:${keycloak-port}/realms/${keycloak-realm}
auth-props:
  issuers:
    - uri: ${keycloak-issuer}
      username-json-path: $.preferred_username
      claims:
        - jsonPath: $.realm_access.roles
        - jsonPath: $.resource_access.*.roles
server:
  port: 9180
  error:
    include-binding-errors: always
    include-message: always
  ssl:
    enabled: false
spring:
  config:
    activate:
      on-profile: develop
  datasource:
    url: jdbc:postgresql://localhost:5432/twister
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12345678
    dbcp2:
      initial-size: 5
      max-total: 100
      max-idle: 30
  liquibase:
    enabled: true
    default-schema: public
    change-log: classpath:db/changelog/db.changelog-master.xml
    test-rollback-on-update: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate.format_sql: true
        hibernate.use_sql_comments: true
  mvc:
    static-path-pattern: /resources/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak-issuer}
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: DEBUG
springdoc:
  swagger-ui:
    url: /resources/swagger.yaml
    syntax-highlight:
      activated: true
    oauth:
      use-pkce-with-authorization-code-grant: true
      client-id: browser
      client-secret: pPJjW65hH7Qsb0zVqRThgjznA6IJKgxi
      realm: ${keycloak-realm}
    csrf:
      enabled: true
---
scheme: https
keycloak-issuer: ${scheme}://${keycloak-host}:${keycloak-port}/realms/${keycloak-realm}
auth-props:
  issuers:
    - uri: ${keycloak-issuer}
      username-json-path: $.preferred_username
      claims:
        - jsonPath: $.realm_access.roles
        - jsonPath: $.resource_access.*.roles
server:
  error:
    include-binding-errors: always
    include-message: always
  ssl:
    enabled: true
spring:
  config:
    activate:
      on-profile: production
  datasource:
    jndi-name: jdbc/PostgressResourceTwisterDS
  liquibase:
    enabled: true
    default-schema: public
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    static-path-pattern: /resources/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak-issuer}
logging:
  level:
    org:
      springframework:
        web: ERROR
      hibernate: ERROR
springdoc:
  swagger-ui:
    url: /resources/swagger.yaml
    syntax-highlight:
      activated: true
    oauth:
      use-pkce-with-authorization-code-grant: true
      client-id: ${swagger-client-id}
      client-secret: ${swagger-keycloak-secret}
      realm: ${keycloak-realm}
    csrf:
      enabled: true