---
scheme: http
origins:
keycloak-port: 8180
keycloak-issuer: ${scheme}://localhost:${keycloak-port}/realms/twister
auth-props:
  issuers:
    - uri: ${keycloak-issuer}
      username-json-path: $.preferred_username
      claims:
        - jsonPath: $.realm_access.roles
        - jsonPath: $.resource_access.*.roles
server:
  port: 9080
  error:
    include-message: always
  ssl:
    enabled: false
spring:
  config:
    activate:
      on-profile: develop
  datasource:
    url: jdbc:postgresql://localhost:5433/twister
    driver-class-name: org.postgresql.Driver
    username: anyway
    password: 12345
    dbcp2:
      initial-size: 5
      max-total: 100
      max-idle: 30
  liquibase:
    enabled: true
    default-schema: public
    change-log: classpath:db/changelog/db.changelog-master.xml
    test-rollback-on-update: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate.format_sql: true
        hibernate.use_sql_comments: true
  mvc:
    static-path-pattern: /resources/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak-issuer}
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: DEBUG
---
scheme: https
origins: http://localhost:9080, http://localhost:8080, http://localhost:8180
keycloak-port: 8443
keycloak-issuer: ${scheme}://localhost:${keycloak-port}/realms/twister
auth-props:
  issuers:
    - uri: ${keycloak-issuer}
      username-json-path: $.preferred_username
      claims:
        - jsonPath: $.realm_access.roles
        - jsonPath: $.resource_access.*.roles
server:
  port: 9080
  error:
    include-message: always
  ssl:
    enabled: true
spring:
  config:
    activate:
      on-profile: production
  datasource:
    jndi-name: jdbc/PostgressUsersDS
  liquibase:
    enabled: true
    default-schema: public
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    static-path-pattern: /resources/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak-issuer}
logging:
  level:
    org:
      springframework:
        web: ERROR
      hibernate: ERROR